WRT-15-PriceDisplay
tradingview/rest_integrations_docs pull request #18
Opened 2022-10-17 10:46 UTC by anachuprina

2022-10-19 16:24 UTC, KatPierce requested changes

2022-10-20 08:13 UTC, anachuprina commented on source/data/Symbol_info.rst
> +-  The ``minmovement`` value depends on the price tick chosen: 1, 5, etc.
Вообще оба варианта корректны: `the price tick chosen` и `the chosen price tick` https://www.quora.com/Where-do-I-place-participles

Кмк, `the price tick value` не очень подходит, так как тогда будет повторение с `The ``minmovement`` value`

2022-10-20 08:19 UTC, anachuprina commented on source/data/Symbol_info.rst
> +   This format also has a variety that is a fractional format of the fractional price.
Вместо _that is_ нет, а вот поставить какой-то пунктационный знак скорей всего нужно. The Chicago Manual of Style говорит, что чаще всего ставят [em dash](https://www.chicagomanualofstyle.org/book/ed17/part2/ch06/psec088.html) перед _that is_ и [запятую](https://www.chicagomanualofstyle.org/book/ed17/part2/ch06/psec051.html) после

2022-10-20 14:55 UTC, KatPierce approved these changes

2022-10-21 14:12 UTC, qaosipov requested changes

2022-10-21 14:12 UTC, qaosipov commented on source/data/Symbol_info.rst
> +To manage how the price displays on the chart, use the following parameters in `/symbol_info`_.
~To manage how the price displays on the chart~
To manage how the price is displayed on the chart

2022-10-27 13:21 UTC, qaosipov approved these changes

2022-10-27 13:21 UTC, merged